/*
 * YtelAPI.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YtelAPI.UWP;
using YtelAPI.UWP.Utilities;


namespace YtelAPI.UWP.Models
{
    public class Body3 : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string messageSid;

        /// <summary>
        /// The unique identifier for the sms resource
        /// </summary>
        [JsonProperty("MessageSid")]
        public string MessageSid 
        { 
            get 
            {
                return this.messageSid; 
            } 
            set 
            {
                this.messageSid = value;
                onPropertyChanged("MessageSid");
            }
        }
    }
} 