/*
 * YtelAPI.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YtelAPI.UWP;
using YtelAPI.UWP.Utilities;


namespace YtelAPI.UWP.Models
{
    public class Body13 : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string recordingsid;

        /// <summary>
        /// The unique identifier for a recording.
        /// </summary>
        [JsonProperty("recordingsid")]
        public string Recordingsid 
        { 
            get 
            {
                return this.recordingsid; 
            } 
            set 
            {
                this.recordingsid = value;
                onPropertyChanged("Recordingsid");
            }
        }
    }
} 