/*
 * YtelAPI.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YtelAPI.UWP;
using YtelAPI.UWP.Utilities;


namespace YtelAPI.UWP.Models
{
    public class Body49 : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.ProductCodeEnum? productCode;
        private string startDate;
        private string endDate;
        private string includeSubAccounts;

        /// <summary>
        /// Filter usage results by product type.
        /// </summary>
        [JsonProperty("ProductCode")]
        public Models.ProductCodeEnum? ProductCode 
        { 
            get 
            {
                return this.productCode; 
            } 
            set 
            {
                this.productCode = value;
                onPropertyChanged("ProductCode");
            }
        }

        /// <summary>
        /// Filter usage objects by start date.
        /// </summary>
        [JsonProperty("startDate")]
        public string StartDate 
        { 
            get 
            {
                return this.startDate; 
            } 
            set 
            {
                this.startDate = value;
                onPropertyChanged("StartDate");
            }
        }

        /// <summary>
        /// Filter usage objects by end date.
        /// </summary>
        [JsonProperty("endDate")]
        public string EndDate 
        { 
            get 
            {
                return this.endDate; 
            } 
            set 
            {
                this.endDate = value;
                onPropertyChanged("EndDate");
            }
        }

        /// <summary>
        /// Will include all subaccount usage data
        /// </summary>
        [JsonProperty("IncludeSubAccounts")]
        public string IncludeSubAccounts 
        { 
            get 
            {
                return this.includeSubAccounts; 
            } 
            set 
            {
                this.includeSubAccounts = value;
                onPropertyChanged("IncludeSubAccounts");
            }
        }
    }
} 